name: rail_aid
description: A minimal scaffold of RailAid Flutter app (Firebase-ready)
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  image_picker: ^0.8.6

  geolocator: ^9.0.2
  url_launcher: ^6.1.7

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.0.0 
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.0.0

  # ðŸ‘‡ ADD THIS
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0


flutter_native_splash:
  color: "#000000"  # Transparent
  image: assets/images/app_logo.png
  android: true
  ios: true



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/rail_aid_logo.png
